version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: perkdotcom/application
    container_name: woofr
    ports:
      - 8080:80
      - 8081:8080
    volumes:
      - .:/var/www/html
